# Generated by Django 4.0.1 on 2022-01-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='load_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='total_toll_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
