# Generated by Django 4.0.1 on 2022-01-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('width', models.CharField(max_length=15)),
            ],
            options={
                'unique_together': {('name', 'width')},
            },
        ),
        migrations.CreateModel(
            name='TollStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=25)),
                ('lng', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=10)),
                ('toll_per_cross', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=25)),
                ('lng', models.CharField(max_length=25)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.road')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
